variable "api_gateway_erc_url" {}
variable "ecs_agent_name" {}
variable "secret_manager_id" {}
variable "vpc_id" {}
variable "alb_security_group_id" {}
variable "instance_security_group_id" {}
variable "public_subnet_a_id" {}
variable "public_subnet_b_id" {}
variable "private_subnet_a_id" {}
variable "private_subnet_b_id" {}
